version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  maven: circleci/maven@1.2.0

workflows:
  build-master: 
    jobs:
      - maven/test:
          command: '-X verify'
      - docker/publish:
          image: salsiddiqui/technology-api
          tag: latest