version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: developerexp/technology-api
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  maven-build:  
    docker:
      - image: cimg/openjdk:15.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building technology-api rest service
          command: mvn -B -DskipTests clean package
  docker-build:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Building docker image
          command: |
            docker build -t $IMAGE_NAME:latest . Dockerfile.Dockerfile
  publish-latest:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
            IMAGE_TAG="0.0.1"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  build-master: 
    jobs:
      - maven-build
      - docker-build
      - publish-latest
