version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  maven: circleci/maven@1.2.0
  secrethub: secrethub/cli@1.1.0
  helm: circleci/helm@1.2.0

executors:
  java15:
    docker:
      - image: 'cimg/openjdk:15.0'

workflows:
  build-master: 
    jobs:
      - maven/test:
          executor: java15
      - docker/publish:
          image: thoughtworksdeveloper/technology-api
          tag: 0.0.1
          pre-steps:
            - secrethub/env-export:
                secret-path: thoughtworks-developer/technology-api/dockerhub/user
                var-name: DOCKER_LOGIN
            - secrethub/env-export:
                secret-path: thoughtworks-developer/technology-api/dockerhub/password
                var-name: DOCKER_PASSWORD
          requires:
            - "maven/test"