version: 2.1

jobs:
  maven-build:  
    docker:
      - image: cimg/openjdk:15.0.2
    steps:
      - checkout
      - run:
          name: Building technology-api
          command: mvn -B -DskipTests clean package

workflows:
  build-api: 
    jobs:
      - maven-build